### ISSUE TITLE
Invalid port

### ISSUE THREAD

**Issue by iinc** [FurqanSoftware/node-whois#64]
Came across a weird error. Thought I would let you know.

```
import whois from 'whois'

whois.lookup('judahfamily.org', (err, data) => {
});
```

```
net.js:1048
      throw new RangeError('"port" option should be >= 0 and < 65536: ' + port);
      ^

RangeError: "port" option should be >= 0 and < 65536: //api.fastdomain.com/cgi/whois
    at lookupAndConnect (net.js:1048:13)
    at Socket.connect (net.js:1021:5)
    at Object.connect (net.js:113:35)
    at Object.lookup (\node_modules\whois\index.js:160:22)
    at Socket.<anonymous> (\node_modules\whois\index.js:107:21)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:557:12)
```

nodejs version v8.11.2

whois version ^2.6.0

**Comment by AdamSlack** [comment]
I had the same issue, different lookup address. Issue #65 shows pretty much the same things.

**Comment by AdamSlack** [comment]
I couldn't catch the issue anywhere either, so had to resort to using
```js
    process.on('uncaughtException', function (err) {
        // Do something with Err.
    });
```
Hopefully it gets resolved! :)

**Comment by iinc** [comment]
There are a bunch of domains that cause it. Here are some few more that cause a similar error.

```
currentzoology.org
theorychina.org
mystyle.pro
orangegrove.biz
ceaj.org
rto-ero.org
cms-italia.org
```

**Comment by domahub** [comment]
Another domain that causes this issue--

deine.org

**Comment by ncroese** [comment]
My pull request should fix this issue: https://github.com/FurqanSoftware/node-whois/pull/68

**Comment by Brunovski** [comment]
The error isn't fixed for the domain simo.so

**Comment by Ibrahimtrrc** [comment]
This error still happening ... can we reopen it plz ? 
example domain : clz.do

**Comment by landland** [comment]
Experiencing this error with domains orpheusmusic.com.ng and cityradio.co.bw

**Comment by samohan123** [comment]
It might be coz the **localhost** is not defined with the *required syntax* in the **"hosts"** file of the system.
The file can be located @:

=>            etc/hosts
(above file for ***linux***)
or
=>            c:\ **Windows** \System32\Drivers\ **etc** \ **hosts**
(above file for **Windows**)

i.e. file has some wrong input.

So, Try replacing everything in that file with the text below as this is the default text that was always there in *hosts* file when it worked fine:


127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
fe80::1%lo0	localhost
